// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALTAGl32CpB665Kd_pRiQryUyFo_xxxrg',
    appId: '1:628380597382:web:a111a0f0022310a6636507',
    messagingSenderId: '628380597382',
    projectId: 'chat-ease-4a702',
    authDomain: 'chat-ease-4a702.firebaseapp.com',
    storageBucket: 'chat-ease-4a702.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQXr4YpAztwr-ylEs8YS2pIo9UhVMhoAE',
    appId: '1:628380597382:android:201241d662db9ff0636507',
    messagingSenderId: '628380597382',
    projectId: 'chat-ease-4a702',
    storageBucket: 'chat-ease-4a702.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS0mGEkZYI-CxkhcLe6UGwSnbxUCm46qk',
    appId: '1:628380597382:ios:9a34d315bed46b7f636507',
    messagingSenderId: '628380597382',
    projectId: 'chat-ease-4a702',
    storageBucket: 'chat-ease-4a702.appspot.com',
    iosBundleId: 'com.example.chatEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS0mGEkZYI-CxkhcLe6UGwSnbxUCm46qk',
    appId: '1:628380597382:ios:3794baa4ae33503b636507',
    messagingSenderId: '628380597382',
    projectId: 'chat-ease-4a702',
    storageBucket: 'chat-ease-4a702.appspot.com',
    iosBundleId: 'com.example.chatEase.RunnerTests',
  );
}
